config/routes.rb
Rails.application.routes.draw do
  resources :photos

  resources :microposts

  get 'users/new'

  get 'static_pages/home'

  get 'static_pages/help'
  get 'help' => 'static_pages#help'

  get 'static_pages/explore'
  get 'explore' => 'static_pages#explore'

  get 'static_pages/recipe'
  get 'recipe' => 'static_pages#recipe'

  get 'static_pages/about'
  get 'about' => 'static_pages#about'
  
  get 'logout' => 'sessions#destroy'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users

   root 'static_pages#home'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :file, PictureUploader
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, length: { minimum: 6 }
   
    # Returns the hash digest of the given string.
    def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
    end
    
    def User.new_token
    SecureRandom.urlsafe_base64
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  protect_from_forgery with: :exception
  include SessionsHelper
  
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Details was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Details was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Details was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:title, :description, :file)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
  user = User.find_by(email: params[:session][:email].downcase)
  if user && user.authenticate(params[:session][:password])
  #BCrypt::Password.new(remember_digest).is_password?(remember_token)
  # Log the user in and redirect to the user's show page.
  log_in user
  redirect_to user
  else
  # Create an error message.
  flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
  render 'new'
  end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    render layout: false
  end

  def help
  end

  def explore
  end

  def recipe
  end

  def about
    render layout: false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :current_user, :logged_in?
  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :current_user, only: [:edit, :update]
  
  def index
    @users = User.all
  end

  def show
  @user = User.find(params[:id])
  end
  
  def logged_in?
       current_user != nil
  end
  
  def new
  @user = User.new
  end
  
  def create
  @user = User.new(user_params)
  if @user.save
  log_in @user
  flash[:success] = "Finish updating!"
  redirect_to @user
  else
  render 'new'
  end
  end
  
  def edit
  @user = User.find(params[:id])
  end
  
  def update
  @user = User.find(params[:id])
  if @user.update_attributes(user_params)
    flash[:success] = "Profile updated"
    redirect_to @user 
  # Handle a successful update.
  else
  render 'edit'
  end
  end

  private
  
  def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  # Confirms a logged-in user.
  def logged_in_user
  unless logged_in?
  flash[:danger] = "Please log in."
  redirect_to login_url
  end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
  session.delete(:user_id)
  @current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
# Returns the Gravatar for the given user.
def gravatar_for(user, options = { size: 80 })
gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
size = options[:size]
gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
image_tag(gravatar_url, alt: user.name, class: "gravatar")
end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="www.foodexplore.com">Food Explore</a>
    by <a href="http://adisazizan.kissr.com">Adis Nabawi</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home",   '/' %></li>
      <li><%= link_to "About",   '/about' %></li>
      
      <% if logged_in? %>
      <li><%= link_to "Explore",   '/photos' %></li>
      <li><%= link_to "Recipe", '/recipe' %></li>
      <li><%= link_to "Help",   '/help' %></li>
      <% else %>
      <li></li>
      <li></li>
      <li></li>
    <% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
 <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

<style>
  
  	.a#hover{
  	  color:#fff;
  	}
  	
  	.navbar-default .nav > li>a,
    .navbar-default .nav>li>a:focus {
    font-size: 13px;
    font-weight: 400;
    color: #fff;
}
}

</style>


<header id="navbar" class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    
     <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="/">FOOD EXPLORE</a>
    </div>
    
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        
        <li><%= link_to "Home",   '/' %></li>
                    
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
        
         <li>
                        <a class="page-scroll" href="/about">About</a>
                    </li>
                    
                    <% if logged_in? %>
                    <li>
                        <a class="page-scroll" href="/photos">Explore</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/recipe">Recipe</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/help">Help</a>
                    </li>
                    <% else %>
                      <li></li>
                      <li></li>
                      <li></li>
                    <% end %>
                    
      </ul>
    </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
       <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Microposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/photos/_form.html.erb
<title>Create new</title>
<%= form_for @photo, :html => {:multipart => true} do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--<div class="field">-->
  <div class="form-group">
    <%= f.label :title %><br>
   <%= f.text_field :title, class:'form-control' %>
  </div>
  <!--<div class="field">-->
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class:'form-control' %>
  </div>
  <!--<div class="field">-->
  <div class="form-group">
    <%= f.label :file %><br>
   <%= f.file_field :file%>
  </div>
  <div class="actions">
    <%= f.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<title>Explore</title>
<h1>Funky Restaurant <a href="/photos/new" class="btn btn-primary" style="color:#fff">Create New</a></h1>

<% @photos.in_groups_of(3) do |group| %>
  <div class="row">
    <% group.compact.each do |photo| %>
      <div class="col-xs-4">
        <%= image_tag photo.file_url, :width => '100px' if photo.file.present?%>
        <h4><%= link_to photo.title, photo %></h4>
        <%= photo.description %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/photos/new.html.erb
<h1>New Place</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<title><%= @photo.title%></title>
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-xs-9">
    <%= image_tag(@photo.file_url, :width => "100%") if @photo.file.present? %>
  </div>

  <div class="col-xs-3">
    <p><b>Name: </b><%= @photo.title%></p>
    <p><b>Description: </b><%= @photo.description %></p>
    <p>
      <%= link_to 'Edit', edit_photo_path(@photo) %> |
      <%= link_to 'Delete', @photo, confirm: 'Are you sure?', method: :delete %> |
      <%= link_to 'Back', photos_path %>
    </p>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
        <title>About Food Hunter</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <meta name="description" content="Food Hunt" />
        <meta name="author" content="Codrops" />
         <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="css/animate.min.css" type="text/css">

   
        <link rel="stylesheet" type="text/css" href="css/demo.css" />
        <link rel="stylesheet" type="text/css" href="css/style1.css" />
		<script type="text/javascript" src="js/modernizr.custom.86080.js"></script>
    </head>
    <body id="page">
      <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="/">FOOD EXPLORE</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                  <li>
                        <a class="page-scroll" href="/">Home</a>
                    </li>
                    
                  <% if logged_in? %>
                  <li><%= link_to "Users", users_path %></li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Profile", current_user %></li>
                      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                      <li class="divider"></li>
                      <li>
                        <%= link_to "Log out", logout_path, method: "delete" %>
                      </li>
                    </ul>
                  </li>
                <% else %>
                  <li><%= link_to "Log in", login_path %></li>
                <% end %>
                    
                    <li>
                        <a class="page-scroll" href="#">About</a>
                    </li>
                    
                    <% if logged_in? %>
                    <li>
                        <a class="page-scroll" href="/photos">Explore</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/recipe">Recipe</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/help">Help</a>
                    </li>
                    <% else %>
                      <li></li>
                      <li></li>
                      <li></li>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
        <ul class="cb-slideshow">
            <li><span>Image 01</span><div><h3>Own the place</h3><p>A funky place where no one knows and share your secret with your friends</p></div></li>
            <li><span>Image 02</span><div><h3>Food Mania</h3><p>Delicacies of your choice now will be easier to find.</p></li></div>
            <li><span>Image 03</span><div><h3>Culinary Master</h3><p>Learn from others recipe and show off to your friends. Become the new star of chefs</p></li></div>
            
        </ul>
        <div class="container">
            <!-- Codrops top bar -->
           
            <header>
            
				
            </header>
        </div>
         <script src="js/jquery.js"></script>
        <script src="js/bootstrap.min.js"></script>
    </body>
</html>

app/views/static_pages/explore.html.erb
<title>Explore</title>
<h1>StaticPages#explore</h1>
<p>Find me in app/views/static_pages/explore.html.erb</p>

app/views/static_pages/help.html.erb
<title> Help </title>
<h1>Register your friends</h1>
<p>To register your friends its easy. Just use this link and register it for them </p>
<button class="btn btn-primary btn-xl page-scroll" onclick="myFriend()">Register your friends</button>

<script>
  function myFriend(){
    window.location.href = 'http://foodexplore.herokuapp.com/users/new';
  }
</script>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Food Hunter</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="css/animate.min.css" type="text/css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="css/creative.css" type="text/css">

  
</head>

<body id="page-top" style="background-color:#f05f40">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="/">Food Explore</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                  <li>
                        <a class="page-scroll" href="/">Home</a>
                    </li>
                    
                  <% if logged_in? %>
                  <li><%= link_to "Users", users_path %></li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Profile", current_user %></li>
                      <li><%= link_to "Settings",  edit_user_path(current_user) %></li>
                      <li class="divider"></li>
                      <li>
                        <%= link_to "Log out", logout_path, method: "delete" %>
                      </li>
                    </ul>
                  </li>
                <% else %>
                  <li><%= link_to "Log in", login_path %></li>
                <% end %>
                    
                    
                    <li>
                        <a class="page-scroll" href="/about">About</a>
                    </li>
                    
                    <% if logged_in? %>
                    <li>
                        <a class="page-scroll" href="/photos">Explore</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/recipe">Recipe</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/help">Help</a>
                    </li>
                    <% else %>
                      <li></li>
                      <li></li>
                      <li></li>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1>Your Favorite Source for Food Hunt</h1>
                <hr>
                <p>Start your search now and experience the funky way of life and enjoy the food</p>
                <a href="/about" class="btn btn-primary btn-xl page-scroll">Find Out More</a>
            </div>
        </div>
    </header>
   
    <!--<br>-->
    <!--<footer class="footer" align="center" style="color:#fff">-->
    <!--    The <a href="www.foodexplore.com" style="color:#fff; font-weight:bold">Food Explore</a>-->
    <!--    by <a href="http://adisazizan.kissr.com" style="color:#fff; font-weight:bold">Adis Nabawi</a>-->
    <!--</footer>-->


    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="js/jquery.easing.min.js"></script>
    <script src="js/jquery.fittext.js"></script>
    <script src="js/wow.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/creative.js"></script>

</body>

</html>

app/views/users/edit.html.erb
<!--provide(:title, "Edit user")-->
<title>Update Profile</title>
<h1>Update your profile</h1>
<div class="row">
<div class="col-md-6 col-md-offset-3">
<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages' %>

<div class="gravatar_edit">
<%= gravatar_for @user %>
<a href="http://gravatar.com/emails" target=_blank>change</a>
</div>
<br>

<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %>
<%= f.label :email %>
<%= f.email_field :email, class: 'form-control' %>
<%= f.label :password %>
<%= f.password_field :password, class: 'form-control' %>
<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation, class: 'form-control' %>
<br>
<%= f.submit "Save changes", class: "btn btn-primary" %>
<% end %>

</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<ul class="users">
<% @users.each do |user| %>
<li>
<%= gravatar_for user, size: 50 %>
<%= link_to user.name, user %>
</li>
<br>
<% end %>
</ul>

app/views/users/new.html.erb
<title>Sign up</title>
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
<div class="col-md-6 col-md-offset-3">
<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages' %>
<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %>
<%= f.label :email %>
<%= f.email_field :email, class: 'form-control' %>
<%= f.label :password %>
<%= f.password_field :password, class: 'form-control' %>
<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation, class: 'form-control' %>
<br>
<%= f.submit "Create my account", class: "btn btn-primary" %>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<title>Profile: <%=  @user.name %></title>
<h1>
<%= gravatar_for @user %>
<%= @user.name %>
</h1>
<b>Email:</b><%= @user.email %>